# .github/workflows/publish.yml
name: Publish to JSR

on:
  workflow_run:
    workflows: ["CI Tests"]  
    types: 
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    steps:
      - uses: actions/checkout@v4

      - name: Publish package
        run: npx jsr publish